### ISSUE TITLE
MAJOR ISSUE!!!!!!!!!!!

### ISSUE THREAD

**Issue by Vivek-Aggala** [dhruvnps/lmc-runner#3]
I have no issue with this repository, but I have one with the repository crudely named can-of-steel.
As I have said in that repository, you have not credited your sponsors to your project. After acknowledging the issue you have not only refused to take any action to solve it, but you have also closed the conversation. Well to that I say, YOU SHALL NOT SILENCE THE PEOPLE. I have now notified my superiors of this issue of catastrophic proportion, and you will be prosecuted in a court of law.

An exceedingly concerned citizen.

**Comment by dhruvnps** [comment]
**This issue is off-topic and will be flagged as spam.**

"I have no issue with this repository" is in clear violation of the following Github community guideline(s):

> **Be clear and stay on topic** - People use GitHub to get work done and to be more productive. Off-topic comments are a distraction (sometimes welcome, but usually not) from getting work done and being productive. Staying on topic helps produce positive and productive discussions.

Any further violations will result in the permanent blocking and reporting of the account @Vivek-Aggala.
